
-- Quotes that get displayed on-screen at the start & end of matches
-- Thanks to Stylis Studios for coming/typing up most of these, the rest are pulled from online.
-- Some of which were typed up by staff at Saturn Developments

local quotes = {
	"There were two kinds of strength. One was the strength that came with having something to protect. The other was the strength of having nothing to lose.",
	"With death staring you in the face, you truly understand what it means to be alive.",
	"People are mirrors. If you smile, a smile will be reflected.",
	"An apple a day keeps any one away, if you throw it hard enough!",
	"People who use others are stupid, but people who are used are even more stupid.",
	"No idiot would want to be friends with an unmoving, unspeaking telephone pole. However, unmoving and unspeaking is exactly what you'd want from a telephone pole.",
	"Most non-NEET people in the world don't realize that human nature isn't scalar, but vectorial.",
	"There's only one difference between heroes and mad men. It's whether they win or lose.",
	"Having people acknowledge your existence is a wonderful thing.",
	"Greed may not be good, but it's not so bad either. You humans think greed is just for money or power, but everyone wants something they can't have.",
	"A little bit of trouble keeps life from being boring.",
	"A problem is not a problem as long as nobody sees it as one.",
	"There are some things you'll never see if you're always running.",
	"Anything can be a sword if you polish it enough.",
	"Even now, twenty centuries after the death of Christ, the world is a long way from peace.",
	"Friends are like balloons. Once you let them go, you can't get them back. So I'm going to tie you to my heart, so to never lose you.",
	"Romance can strengthen people, but it can also make them useless.",
	"The past makes you wanna die out of regret and future makes you depressed out of anxiety. So by elimination, the present is likely the happiest time.",
	"The time when you're happy is also the time when you're afraid that the happiness will end.",
	"The things we can't obtain are the most beautiful ones.",
	"The difference between the novice and the master is that the master has failed more times than the novice has tried.",
	"The ideal tool for controlling people is fear. And nothing overwhelms people more than an unseen fear.",
	"It's called a miracle because it doesn't happen.",
	"...Without love, it cannot be seen? ...Hah. That's backwards... Because of love, you end up seeing things that don't even exist.",
	"People with talent often have the wrong impression that things will go as they think.",
	"The only ones who should kill are those who are prepared to be killed!",
	"War does not determine who is right - only who is left.",
	"I dream of a better tomorrow, where chickens can cross the road and not be quested about their motives",
	"No I didn't trip, the floor looked like it needed a hug",
	"Better late than never, but never late is better",
	"I was standing in the park wondering why frisbees got bigger as they get closer. Then it hit me.",
	"When tempted to fight fire with fire, remember that the fire department generally uses water.",
	"Never underestimate the power of stupid people in large groups",
	"A successful man is one who makes more money than his wife can spend. A successful woman is one who can find such a man.",
	"Behind every great man is a woman rolling her eyes.",
	"Perfection is not attainable, but if we chase perfection we can catch excellence.",
	"An idea isn't responsible for the people who believe in it.",
	"I would like to die on Mars. Just not on impact.",
	"If women ran the world we wouldn't have wars, just intense negotiations every 28 days. [Robin Williams]",
	"Between two evils, I always pick the one I never tried before.",
	"If two wrongs don't make a right, try three.",	
	"Man cannot live by bread alone; he must have peanut butter.",
	"A pessimist is a person who has had to listen to too many optimists.",
	"Any kid will run any errand for you, if you ask at bedtime.",
	"Guilt: the gift that keeps on giving.",
	"The point of war is not to die for your country, but to make the noob on the other side die for his",
	"Always borrow money from a pessimist. He won't expect it back.",
	"Knowledge is knowing a tomato is a fruit; wisdom is not putting it in a fruit salad.",
	"I asked God for a bike, but I know God doesn't work that way. So I stole a bike and asked for forgiveness.",
	"The best way to lie is to tell the truth . . . carefully edited truth.",
	"Do not argue with an idiot. He will drag you down to his level and beat you with experience.",
	"A bargain is something you don't need at a price you can't resist.",
	"Children: You spend the first 2 years of their life teaching them to walk and talk. Then you spend the next 16 telling them to sit down and shut-up.",
	"When you go into court you are putting your fate into the hands of twelve people who weren't smart enough to get out of jury duty.",
	"Those people who think they know everything are a great annoyance to those of us who do.",
	"By working faithfully eight hours a day you may eventually get to be boss and work twelve hours a day.",
	"When tempted to fight fire with fire, remember that the Fire Department usually uses water.",
	"America is a country where half the money is spent buying food, and the other half is spent trying to lose weight.",
	"A bank is a place that will lend you money, if you can prove that you don't need it.",
	"The best time to give advice to your children is while they're still young enough to believe you know what you're talking about.",
	"Tell a man there are 300 billion stars in the universe and he'll believe you. Tell him a bench has wet paint on it and he'll have to touch it to be sure.",
	"The human brain is a wonderful thing. It starts working the moment you are born, and never stops until you stand up to speak in public.",
	"At every party, there are two kinds of people'those who want to go home and those who don't. The trouble is, they are usually married to each other.",
	"You love flowers, but you cut them. You love animals, but you eat them. You tell me you love me, so now I'm scared!",
	"I don't need a hair stylist, my pillow gives me a new hairstyle every morning.",
	"Don't worry if plan A fails, there are 25 more letters in the alphabet.",
	"Studying means 10% reading and 90% complaining to your friends that you have to study.",
	"If you want your wife to listen to you, then talk to another woman; she will be all ears.",
	"You never realize how boring your life is until someone asks what you like to do for fun.",
	"In the morning you beg to sleep more, in the afternoon you are dying to sleep, and at night you refuse to sleep.",
	"When I said that I cleaned my room, I just meant I made a path from the doorway to my bed.",
	"Life isn't measured by the number of breaths you take, but by the number of moments that take your breath away.",
	"The great pleasure in life is doing what people say you cannot do.",
	"If we were on a sinking ship, and there was only one life vest... I would miss you so much.",
	"All my life I thought air was free, until I bought a bag of chips.",
	"Long time ago I used to have a life, until someone told me to create a Facebook account.",
	"Now now, don't forget the chore Mom gave you ten minutes ago.",
	"Never take life seriously. Nobody gets out alive anyway.",
	"An enemy is somebody who has a story you haven't heard of yet.",
	"Anything we do not understand is considered to be the devil.",
	"The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
	"Aim for the moon. If you miss, you may hit a star.",
	"Don't watch the clock; do what it does. Keep going.",
	"'Sometimes, I dream of cheese.'	- Half-Life 2 Refugee",
	"Gabe Newell is not the hero we wanted, but the hero we needed.",
	"Bullet drop exists, people.",
	"Corey is stonki  - Alan the liar",
	"Your computer will restart outside of active hours to install updates	  -- Windows 11",
	"Try a Mac		- Apple and Microsoft", -- not really but for the love of god try one
}

return quotes
